### ISSUE TITLE
Support Self-Signed Certs

### ISSUE THREAD

**Issue by lexfrei** [v-zhuravlev/zabbix-notify#11]
Hello!
In my case i have to use it throw proxy, so certs never valid.
Please, add key to allow this.

Workaround:
`$ENV{'PERL_LWP_SSL_VERIFY_HOSTNAME'} = 0;` in hipchat lib

**Comment by v-zhuravlev** [comment]
hi try this version: https://github.com/v-zhuravlev/zabbix-notify/commit/3d17fac5a6b8ccb97ca8013131280cf14ff7b37b
use key `--no-ssl_verify_hostname`

**Comment by v-zhuravlev** [comment]
@lexfrei , please tell me how it goes

**Comment by lexfrei** [comment]
@v-zhuravlev i can't test it right now. Wait for monday plz.

**Comment by lexfrei** [comment]
Looks good. Feel free to resolve
