### ISSUE TITLE
Condition "Trigger Value = PROBLEM"

### ISSUE THREAD

**Issue by prsf1233** [v-zhuravlev/zabbix-notify#14]
Hi, in Zabbix 3.2 they removed the Trigger Value condition which breaks the script. What would you suggest would be the bext way to resolve this?

Thanks
Graham

**Comment by v-zhuravlev** [comment]
Sorry, I think it worked in 3.2. Or did you meant 3.4? Can you please provide an example?

**Comment by prsf1233** [comment]
Hi, definitely 3.2.

[image: Inline images 1]

**Comment by prsf1233** [comment]
Hi, any thoughts on whether we can fix this? I will need to find a new solution for my project otherwise.
Thanks

**Comment by v-zhuravlev** [comment]
what happens if you use it without trigger value? What system are you notifying?

**Comment by v-zhuravlev** [comment]
https://www.zabbix.com/forum/showthread.php?t=55685

**Comment by prsf1233** [comment]
I found the problem by a combination of setting debug level to 4 for the alerter but also looking at the contents of the alerts table in the Zabbix database. I could then see the media type was not defined for the user group I was sending the alert to. Doh ... user error.
