### ISSUE TITLE
Slack Mode Alert do not work properly.

### ISSUE THREAD

**Issue by md2k** [v-zhuravlev/zabbix-notify#16]
Problem with Alert mode that it do not delete all previous notifications for specific EventID.
For example if i have Alert with EventID 1 and after that REcovery Event, all work ok. Alert removed, OK State posted after while it also removed. 
Problem happening when ACK event fired. 
we Have Alert message, after that we have ACK Message (some time can be more than one ACKs)
On recovery message zabbix-notify removes only last related message (last ACK message), so all previous messages for same EventID remains.

**Comment by v-zhuravlev** [comment]
so its 3.4 ack message, ok, will try to fix it

**Comment by v-zhuravlev** [comment]
@md2k, can you give me example what's in your ACK message template in Zabbix?

**Comment by v-zhuravlev** [comment]
It seems taht ACK messages are not currently supported. As only last message with eventid is updated and deleted. 

I think that ACK messages should append original alarm message instead of creating new one. And then recovery would delete all that. What do you think?

**Comment by ZeroPhi** [comment]
I have been trying to figure out how to have ACK messages working without creating a new one (alarm), mind you I've only been at this for 2 days in my spare time. So far the only thing I attempted was duplicating the OK message code, removing the delete portion, and having that edit the message as it does when an OK message is sent. No Luck.. (I'm new to coding in general) I was just having it repeat the recovery message with a few modifications for the ACK, that way it had the same format as the original alarm. 

@v-zhuravlev But I do like the idea of having the ACK messages appear using threading, below is an example of the ACK message mine was sending, again it is a copy of the default recovery message, just modified. I will continue to work on it in my spare time (which isn't much, plus I'm learning), if I do manage to get something working I will shoot it your way.

``` 
{
            "fallback": "[[{HOST.NAME}:{TRIGGER.NAME}:{STATUS}]]",
            "pretext": "Acknowledged",
            "author_name": "[[{HOST.NAME}]] - [[{HOST.DNS}]]",
            "title": "[[{TRIGGER.NAME}]]",
            "title_link": "http://ZABBIXSERVER.COM/tr_events.php?triggerid={TRIGGER.ID}&eventid={EVENT.RECOVERY.ID}",
            "text": "[[{TRIGGER.DESCRIPTION}]]",
            "fields": [
                {
                    "title": "Status",
                    "value": "{STATUS}",
                    "short": true
                },
                {
                    "title": "Severity",
                    "value": "{TRIGGER.SEVERITY}",
                    "short": true
                },
                {
                    "title": "Time",
                    "value": "{EVENT.DATE} {EVENT.TIME}",
                    "short": true
                },
				{
                    "title": "Location",
                    "value": "{INVENTORY.LOCATION}",
                    "short": true
                },
				{
                    "title": "Asset Tag",
                    "value": "{INVENTORY.ASSET.TAG}",
                    "short": true
                },
                {
                    "title": "EventID",
                    "value": "eventid: {EVENT.ID}",
                    "short": true
                },
                {
                    "title": "Event Acknowledgement history",
                    "value": "[[{EVENT.ACK.HISTORY}]]",
                    "short": false
                }, 
                {
                    "title": "Escalation history",
                    "value": "[[{ESC.HISTORY}]]",
                    "short": false
                }

                
                
            ]
        }
```

**Comment by drakonstein** [comment]
I'm coming across the same problem where using `--slack_mode=alarm` does not act any differently from the default event mode.  Is there any additional testing that would be helpful for this?  I have this all set up in my home/test environment and changes are very easy to do.

**Comment by v-zhuravlev** [comment]
just make sure you have Eventid: {EVENT.ID} in your ack message as well.

**Comment by drakonstein** [comment]
Will the default line of `Original event ID: {EVENT.ID}` work for that or does it need to be explicitly `Eventid: {EVENT.ID}`?

**Comment by ZeroPhi** [comment]
I was able to perform some testing this week, looks like you need to have Eventid: {EVENT.ID} in both the Operations message and the ack message or else it will just send the ack into slack as if you are using the Event option and fail to delete the original message and ack messages. So far seems to be working from my testing... I now need to move it to Production and will update if I run into any other issues.

@v-zhuravlev Thank you again and as a side note, noticed in the readme you have both --nofork and --no-fork

**Comment by v-zhuravlev** [comment]
Hi, thanks for noting, you can fix readme problems yourself - just click edit and fix it - this will create a pull request . I Would appreciate that 

Отправлено с телефона

**Comment by v-zhuravlev** [comment]
@drakonstein ,
https://github.com/v-zhuravlev/zabbix-notify/blob/master/bin/zbx-notify#L134
you need to have `eventid: {EVENT.ID}` in lower or uppercase somewhere in your message/recovery/ack. Thats all.
