### ISSUE TITLE
Script fails during initial test

### ISSUE THREAD

**Issue by tmroberts-tableau** [v-zhuravlev/zabbix-notify#22]
I'm trying to set your script up and i've gone through all of the steps.  When I try to run it through the first test it fails with this:

Can't locate JSON/XS.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/local/share/perl5/SlackBot.pm line 9.
BEGIN failed--compilation aborted at /usr/local/share/perl5/SlackBot.pm line 9.
Compilation failed in require at ./zbx-notify line 8.
BEGIN failed--compilation aborted at ./zbx-notify line 8.

I have installed, removed, reinstalled, double reinstalled everything that you instruct to install and I just can't quite figure out where the disconnect is.

I'm running RHEL7 and Zabbix 3.4 and I assume that what ever we are using for Slack is the latest.  Our slack guys told me that at first glance it looks like you are trying to use and "old" API key version?  Not really sure about that, but, I would really love some insight to what needs to be done to fix this.

**Comment by v-zhuravlev** [comment]
Hi, you are missing JSON-XS module as error states:
`Can't locate JSON/XS.pm`
do: 
`yum install perl-JSON-XS perl-libwww-perl perl-LWP-Protocol-https`

**Comment by tmroberts-tableau** [comment]
I have tried several times to install that already.

**Comment by v-zhuravlev** [comment]
perl Packets installed in Centos7/RHEL7 with yum might not be visible under root. Thats probably the case.

**Comment by eirisdg** [comment]
As info, perl-JSON-XS is in epel repo
