### ISSUE TITLE
Macro in Subject

### ISSUE THREAD

**Issue by zetheroo** [v-zhuravlev/zabbix-notify#24]
Zabbix to HipChat:

{TRIGGER.NAME} is set in the Subject of the message to be sent, and the Trigger name is another Macro, {ITEM.LASTVALUE}. It seems that this doesn't work. I get 'Subject provided is wrong' when Action attempts to send notification.

If the Trigger name is just plain text then {TRIGGER.NAME} in the Subject works fine.
I also noticed however that {ITEM.LASTVALUE} in the Subject does not work, while {HOST.NAME} does work.

**Comment by v-zhuravlev** [comment]
you need to wrap macros in [[ ]] . See README
