### ISSUE TITLE
Why is this so complicated?

### ISSUE THREAD

**Issue by rodizio1** [v-zhuravlev/zabbix-notify#32]
This other solution seems so much simpler: https://aperogeek.fr/zabbix-send-alerts-to-slack/

What are the benefits of zabbix-notify?

**Comment by v-zhuravlev** [comment]
- you can delete/update already posted alarms in slack
- you can join alarms (problem, acknowledgements, resolve) together using Slack threads/
- you can post plain JSON to Slack API to fine tune formatting in Slack... See README for all features.

**Comment by psyborg55** [comment]
@rodizio1 Hi, can you send me an email? Could not find yours or someone from EZ wifi broadcast contact email..
