### ISSUE TITLE
Severity & status should probably also be derived from the subject

### ISSUE THREAD

**Issue by ukjbrown** [v-zhuravlev/zabbix-notify#6]
If you remove the severity and status from the message body and only have them in the subject, the parsing doesn't pick them up. Consequently, color coding is incorrect.

It would be useful if the script looked in both the subject and message body for these values as there's not much use in repeating them in both the subject and message.

Sorry, I'm feeling too lazy to fork and submit a pull request.

**Comment by v-zhuravlev** [comment]
Hi, https://github.com/v-zhuravlev/zabbix-notify/commit/3b94e7835f0a169be95d5d193377d13c59c164ea adds this feature
